version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    volumes:
      - app_status:/status
      - app_storage:/app/storage
      - ./:/app

  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: supersecret
    volumes:
      - db_data:/var/lib/mysql

  cache:
    image: redis

volumes:
  app_storage:
    driver: local
  app_status:
    driver: local
  db_data:
    driver: local
